DROP DATABASE IF EXISTS ma_bdd;

CREATE DATABASE IF NOT EXISTS ma_bdd;

USE ma_bdd;

CREATE TABLE Users(
Id INT PRIMARY KEY AUTO_INCREMENT,
Nom VARCHAR(20) NOT NULL,
Prenom VARCHAR(20) NOT NULL,
Telephone VARCHAR(10)
);

CREATE TABLE Command(
id INT PRIMARY KEY AUTO_INCREMENT,
produit VARCHAR(20) NOT NULL,
id_user INT NOT NULL,
FOREIGN KEY (id_user) REFERENCES Users(Id)
);
